version: '3.5'
services:
  jira:
    image: cptactionhank/atlassian-jira-software
    depends_on:
      - postgres
    environment:
      - X_PROXY_NAME=${DOMAIN}
      - X_PROXY_PORT=443
      - X_PROXY_SCHEME=https
    networks:
      - jira-net
      - proxy
    volumes:
      - ./jira:/var/atlassian/jira
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jira.entrypoints=http"
      - "traefik.http.routers.jira.rule=Host(`${DOMAIN}`)"
      - "traefik.http.middlewares.jira-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.jira.middlewares=jira-https-redirect"
      - "traefik.http.routers.jira-https.entrypoints=https"
      - "traefik.http.routers.jira-https.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.jira-https.tls=true"
      - "traefik.http.routers.jira-https.tls.certresolver=http"
      - "traefik.http.routers.jira-https.service=${SERVICENAME}"
      - "traefik.docker.network=proxy"
    restart: unless-stopped
 
  db:
    image: mysql:5.6
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD}
    networks:
      - jira-net
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped
volumes:
  jira:
  postgres:
networks:
  jira-net:
  proxy:
    external: true

